const maker_ids = {
  "3t": "3T",
  "addmotor": "AddMotor",
  "aegis": "Aegis",
  "airborne": "Airborne",
  "airdrop": "Airdrop",
  "alchemy": "Alchemy",
  "allcity": "All-City",
  "allied": "Allied",
  "alutech": "Alutech",
  "amego": "Amego",
  "amflow": "AMFLOW",
  "ancheer": "Ancheer",
  "antidote": "Antidote",
  "apollo": "Apollo",
  "arc8": "ARC8",
  "argon18": "Argon 18",
  "argonaut": "Argonaut",
  "ari": "ARI",
  "arielrider": "Ariel Rider",
  "atherton": "Atherton",
  "aurai": "Aurai",
  "aventon": "Aventon",
  "banshee": "Banshee",
  "barracuda": "Barracuda",
  "basis": "Basis",
  "basso": "Basso",
  "batchbicycles": "Batch Bicycles",
  "batribike": "Batribike",
  "bearclaw": "Bearclaw",
  "benno": "Benno",
  "berria": "Berria",
  "bianchi": "Bianchi",
  "biktrix": "Biktrix",
  "bird": "Bird",
  "blix": "Blix",
  "bluejay": "Bluejay",
  "bmc": "BMC",
  "boardman": "Boardman",
  "bold": "Bold",
  "bombtrack": "Bombtrack",
  "borealis": "Borealis",
  "bpmimports": "BPM Imports",
  "breezer": "Breezer",
  "bridgebikeworks": "Bridge Bike Works",
  "brodie": "Brodie",
  "brompton": "Brompton",
  "brooklynbicycleco": "Brooklyn Bicycle Co.",
  "bulls": "Bulls",
  "bunchbikes": "Bunch Bikes",
  "buzz": "Buzz",
  "byocycles": "Byocycles",
  "c3strom": "C3STROM",
  "cairn": "Cairn",
  "calibre": "Calibre",
  "californiabicyclefactory": "California Bicycle Factory",
  "canfield": "Canfield",
  "cannondale": "Cannondale",
  "canyon": "Canyon",
  "carqon": "Carqon",
  "carver": "Carver",
  "casati": "Casati",
  "cero": "CERO",
  "cervelo": "Cervélo",
  "charge": "Charge",
  "chromag": "Chromag",
  "cinelli": "Cinelli",
  "cipollini": "Cipollini",
  "civibikes": "CIVI BIKES",
  "claudbutler": "Claud Butler",
  "cleary": "Cleary",
  "colnago": "Colnago",
  "commencal": "Commencal",
  "comotion": "Co-Motion",
  "condor": "Condor",
  "coop": "Co-op Cycles",
  "corima": "Corima",
  "corratec": "Corratec",
  "cortina": "Cortina",
  "cowboy": "Cowboy",
  "crussis": "Crussis",
  "cube": "Cube",
  "cuda": "Cuda",
  "curve": "Curve",
  "cycleofgood": "Cycle of Good",
  "dallingridge": "Dallingridge",
  "dartmoor": "Dartmoor",
  "dassi": "Dassi",
  "dawes": "Dawes",
  "delsol": "Del Sol",
  "denago": "Denago",
  "denver": "Denver",
  "deviate": "Deviate",
  "devinci": "Devinci",
  "diamant": "Diamant",
  "diamondback": "Diamondback",
  "dinobikes": "Dino Bikes",
  "dmr": "DMR",
  "dolan": "Dolan",
  "dost": "DŌST",
  "eahora": "Eahora",
  "earlyrider": "Early Rider",
  "earlyriderlimited": "Early Rider Limited",
  "eddymerckx": "Eddy Merckx",
  "eg": "EG",
  "ejoe": "E-Joe",
  "electra": "Electra",
  "electricbikecompany": "Electric Bike Company",
  "electricbiketechnologies": "Electric Bike Technologies",
  "ellsworth": "Ellsworth",
  "elops": "Elops",
  "elux": "Elux",
  "eminent": "Eminent",
  "emojo": "Emojo",
  "emubikes": "EMU Bikes",
  "engwe": "Engwe",
  "enve": "ENVE",
  "enzoebikes": "Enzo eBikes",
  "esker": "Esker",
  "espin": "Espin",
  "eunorau": "Eunorau",
  "evelo": "Evelo",
  "evil": "Evil",
  "evobicycles": "Evo Bicycles",
  "factor": "Factor",
  "fairdale": "Fairdale",
  "falcon": "Falcon",
  "fantic": "Fantic",
  "fara": "Fara",
  "faraday": "Faraday",
  "felt": "Felt",
  "festka": "Festka",
  "fezzari": "Fezzari",
  "flx": "FLX",
  "flyerbyradioflyer": "Flyer by Radio Flyer",
  "foes": "Foes",
  "fondriest": "Fondriest",
  "forbidden": "Forbidden",
  "forestal": "Forestal",
  "forme": "Forme",
  "forth": "Forth",
  "framed": "Framed",
  "freespirit": "Free Spirit",
  "frog": "Frog",
  "fthpower": "FTH Power",
  "fuji": "Fuji",
  "furosystems": "FuroSystems",
  "garneau": "Garneau",
  "garyfisher": "Gary Fisher",
  "gasgas": "GasGas",
  "gazelle": "Gazelle",
  "geometron": "Geometron",
  "gepida": "Gepida",
  "ghost": "Ghost",
  "giant": "Giant",
  "globber": "Globber",
  "gocycle": "Gocycle",
  "gopower": "GoPower",
  "growlerbikes": "Growler Bikes",
  "gt": "GT",
  "guerrillagravity": "Guerrilla Gravity",
  "guru": "Guru",
  "haro": "Haro",
  "head": "HEAD",
  "himiway": "Himiway",
  "holdsworth": "Holdsworth",
  "hopetechnology": "Hope Technology",
  "hudski": "Hudski",
  "huffy": "Huffy",
  "husqvarna": "Husqvarna",
  "ibis": "Ibis",
  "igoelectric": "iGO Electric",
  "intense": "Intense",
  "intense951": "Intense 951",
  "izip": "iZIP",
  "jamis": "Jamis",
  "jetson": "Jetson",
  "juicedbikes": "Juiced Bikes",
  "juliana": "Juliana",
  "jupiterbike": "JupiterBike",
  "k2": "K2",
  "kavenz": "Kavenz",
  "kellys": "Kellys",
  "kestrel": "Kestrel",
  "kettler": "Kettler",
  "khs": "KHS",
  "kidsrideshotgun": "Kids Ride Shotgun",
  "knolly": "Knolly",
  "kona": "Kona",
  "ktm": "KTM",
  "kuota": "Kuota",
  "lapierre": "Lapierre",
  "last": "Last",
  "lauf": "Lauf",
  "lectric": "Lectric",
  "lectricebikes": "Lectric eBikes",
  "leecougan": "Lee Cougan",
  "lekker": "Lekker",
  "lemondbicycles": "LeMond Bicycles",
  "libertytrike": "Liberty Trike",
  "lightweight": "Lightweight",
  "litespeed": "Litespeed",
  "liteville": "Liteville",
  "liv": "Liv",
  "lombardo": "Lombardo",
  "look": "Look",
  "lynskey": "Lynskey",
  "m2s": "M2S",
  "magnum": "Magnum",
  "marin": "Marin",
  "masi": "Masi",
  "mason": "Mason",
  "maxfoot": "Maxfoot",
  "mde": "MDE Bikes",
  "mec": "MEC",
  "meekboyz": "Meekboyz",
  "merida": "Merida",
  "modbikes": "MOD Bikes",
  "momentum": "Momentum",
  "mondraker": "Mondraker",
  "mongoose": "Mongoose",
  "montague": "Montague",
  "moots": "Moots",
  "motiv": "Motiv",
  "motobecane": "Motobecane",
  "nakto": "Nakto",
  "ncm": "NCM",
  "nicolai": "Nicolai",
  "niner": "Niner",
  "nireeka": "Nireeka",
  "norco": "Norco",
  "nordest": "Nordest",
  "ns": "NS Bikes",
  "nukeproof": "Nukeproof",
  "obed": "Obed",
  "ocoee": "Ocoee",
  "ohm": "OHM",
  "open": "OPEN",
  "orange": "Orange",
  "orbea": "Orbea",
  "orro": "Orro",
  "otso": "Otso",
  "oxylane": "Oxylane",
  "pace": "Pace",
  "panorama": "Panorama",
  "parlee": "Parlee",
  "pashley": "Pashley",
  "patrol": "Patrol",
  "pedego": "Pedego",
  "pendleton": "Pendleton",
  "pinarello": "Pinarello",
  "pinnacle": "Pinnacle",
  "pivot": "Pivot",
  "pole": "Pole",
  "polygon": "Polygon",
  "poseidon": "Poseidon",
  "premium": "Premium",
  "prevelo": "Prevelo",
  "prime": "Prime",
  "priority": "Priority",
  "privateer": "Privateer",
  "productionprivee": "Production Privee",
  "propain": "Propain",
  "propella": "Propella",
  "public": "Public",
  "puky": "Puky",
  "pure": "Pure",
  "pyga": "Pyga",
  "qualisports": "Qualisports",
  "quietkat": "QuietKat",
  "quintanaroo": "Quintana Roo",
  "raaw": "Raaw",
  "radio": "Radio",
  "radpowerbikes": "Rad Power Bikes",
  "ragley": "Ragley",
  "raleigh": "Raleigh",
  "rambobikes": "Rambo Bikes",
  "rattan": "Rattan",
  "redline": "Redline",
  "reeb": "REEB",
  "reid": "Reid",
  "revel": "Revel",
  "revolve": "Revolve",
  "ride1up": "Ride1Up",
  "ridgeback": "Ridgeback",
  "ridley": "Ridley",
  "rieseandmuller": "Riese & Müller",
  "ritchey": "Ritchey",
  "riva": "Riva",
  "riverside": "Riverside",
  "rizebikes": "Rize Bikes",
  "rockrider": "Rockrider",
  "rockymountain": "Rocky Mountain",
  "rondo": "Rondo",
  "roodog": "RooDog",
  "rossignol": "Rossignol",
  "rsd": "RSD",
  "sage": "Sage",
  "salsa": "Salsa",
  "santacruz": "Santa Cruz",
  "sava": "Sava",
  "scamp": "Scamp",
  "schwinn": "Schwinn",
  "scor": "SCOR",
  "scott": "Scott",
  "sensa": "Sensa",
  "serial1": "Serial 1",
  "sherpa": "Sherpa",
  "silverback": "Silverback",
  "skorpion": "Skorpion",
  "soma": "Soma",
  "sonder": "Sonder",
  "sondors": "Sondors",
  "soulfastebikes": "Soul Fast eBikes",
  "sparkbikes": "Spark Bikes",
  "sparkcycleworks": "Spark Cycleworks",
  "spawn": "Spawn",
  "specialized": "Specialized",
  "spot": "Spot",
  "stanton": "Stanton",
  "statebicycleco": "State Bicycle Co.",
  "stilus": "Stilus",
  "strider": "Strider",
  "stromer": "Stromer",
  "super73": "Super73",
  "superior": "Superior",
  "surface604": "Surface 604",
  "surly": "Surly",
  "synergy": "Synergy",
  "tenways": "Tenways",
  "tern": "Tern",
  "thesis": "Thesis",
  "thoemus": "Thömus",
  "thok": "Thok",
  "time": "TIME",
  "titus": "Titus",
  "tommaso": "Tommaso",
  "toutterrain": "Tout Terrain",
  "tower": "Tower",
  "trailcraft": "Trailcraft",
  "transition": "Transition",
  "trek": "Trek",
  "trifox": "Trifox",
  "tumbleweed": "Tumbleweed",
  "tunturi": "Tunturi",
  "turboant": "TurboAnt",
  "turner": "Turner",
  "urbanarrow": "Urban Arrow",
  "urbandrivestyle": "Urban Drivestyle",
  "urtopia": "Urtopia",
  "vaast": "VAAST",
  "vandessel": "Van Dessel",
  "vanmoof": "VanMoof",
  "vannicholas": "Van Nicholas",
  "vbike": "VBike",
  "velec": "Velec",
  "ventum": "Ventum",
  "verde": "Verde",
  "viathon": "Viathon",
  "vielo": "Vielo",
  "viking": "Viking",
  "vintageelectric": "Vintage Electric",
  "vitus": "Vitus",
  "voltbike": "VoltBike",
  "voodoo": "Voodoo",
  "votec": "Votec",
  "vvolt": "Vvolt",
  "areone": "Areone",
  "whyte": "Whyte",
  "wiggins": "Wiggins",
  "wildsyde": "Wildsyde",
  "wilier": "Wilier",
  "wisper": "Wisper",
  "woom": "Woom",
  "xn": "XN",
  "xtracycle": "Xtracycle",
  "yamaha": "Yamaha",
  "yeti": "Yeti",
  "yt": "YT",
  "yuba": "Yuba",
  "zen": "Zen",
  "zerode": "Zerode"
};
