# Configuration settings for the BikeRole bot.
# Update this file to change the bot's prefix, activity message, or other settings.
# Do not create new config files; modify this one.

bot:
  name: BikeRole
  description: A Discord bot for bike communities
  version: 1.0.0
  activity_message: "for !role commands"
commands:
  prefix: "!"
  cooldown: 3  # seconds
logging:
  level: INFO
  file: bot.log
api:
  base_url: "https://api.bikenode.com/v1"
  api_key: ""  # Set this via environment variable in production
  timeout: 10  # seconds
webhooks:
  enabled: true
  port: 8080
  secret_key: ""  # Set this via environment variable in production
roles:
  default_color: "0x3498db"  # Blue
  prefix: "Bike-"
data:
  storage_path: "data"
